#!/usr/bin/bash
# Configure shell to use colors
# This doesn't check any vars, it colorizes as much as it can
# Only call if you want colors! (IE figure out whether you want them before sourcing)

# Configure Colors
#  Set colorful PS1 only on colorful terminals.
#  dircolors --print-database uses its own built-in database
#  instead of using /etc/DIR_COLORS.  Try to use the external file
#  first to take advantage of user additions.  Use internal bash
#  globbing instead of external grep binary.

# Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
if type -P dircolors >/dev/null ; then # check to see if the dircolors prog exists
	if [[ -f ~/.dir_colors ]] ; then   # source custom dir colors if defined
		eval $(dircolors -b ~/.dir_colors)
	elif [[ -f /etc/DIR_COLORS ]] ; then # if no custom dir colors, check /etc
		eval $(dircolors -b /etc/DIR_COLORS)
	fi  # don't need to `eval dircolors -b` if no custom files, bc it should have run
fi

BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
PURPLE="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
MAGENTA="\[$(tput setaf 7)\]"
BOLD="\[$(tput bold)\]"
RESET="\[$(tput sgr0)\]"
# export PS1="${GREEN}my prompt${RESET}> "

if [[ ${EUID} != 0 ]] ; then
	# PS1='[\[\033[01;32m\]\t\[\033[00m\]]\$ '
    PS1="${BOLD}${MAGENTA}[${BOLD}${BLUE}\t${RESET}${BOLD}${MAGENTA}]${RESET}$ "
else
	# PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\[\033[00m\]\$'
	PS1='\[\033[01;32m\][\t]\[\033[00m\]\# '

fi

# Color specific aliases already setup in .bash_aliases! (for now)
