#!/usr/bin/python

import sys
import os
import subprocess
from datetime import datetime
import tempfile
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", action="store_true")
args = parser.parse_args(sys.argv[1:])

dt = datetime.now()
ts = dt.strftime("%Y-%m-%d, %H:%M")
fi = tempfile.TemporaryFile()
fi.write(ts)
fi.seek(0)
subprocess.call(["clip"], stdin=fi)
if args.verbose:
    subprocess.call(["notify-send", "Timestamp copied to clipboard: " + ts])
