#!/usr/bin/python2
from __future__ import print_function
#
import argparse
import sys


def argparse_filter_parser():
    '''
    parser for using file in/out convention with
    stdin/stdout being the default
    '''
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('-i', '--input',
                        dest='fin',
                        type=argparse.FileType('r'),
                        default=sys.stdin,
                        help='input file')
    parser.add_argument('-o', '--output',
                        dest='fout',
                        type=argparse.FileType('w'),
                        default=sys.stdout,
                        help='output file')
    return parser


def main(args):
    parser = argparse.ArgumentParser(parents=[argparse_filter_parser()])
    parser.add_argument("-s")
    args = parser.parse_args(args)
    vals = args.fin.read()
    if ',' in vals:
        sep = ','
    elif ':' in vals:
        sep = ':'
    else:
        sep = None
    vals = vals.split(sep)
    for val in vals:
        print(val.strip(), file=args.fout)

if __name__ == '__main__':
    main(sys.argv[1:])
